/**
 * bunker 布局数据，由 tools/import-bunker.ts 从 Overmind 自动生成，不要手改。
 * 来源：https://raw.githubusercontent.com/bencbartlett/Overmind/master/src/roomPlanner/layouts/bunker.ts
 *
 * 坐标是相对锚点的偏移。锚点是 bunker 的正中心，第一个 spawn 落在锚点右侧 4 格。
 * rcl 字段表示这个位置最早在几级可以建，升级时按它过滤就是当次要拍的工地。
 */

export interface BunkerStructure {
  type: BuildableStructureConstant;
  dx: number;
  dy: number;
  rcl: number;
}

/** bunker 整体占 128 格 */
export const BUNKER_STRUCTURES: BunkerStructure[] = [
  { type: "spawn", dx: 4, dy: 0, rcl: 1 },
  { type: "container", dx: 2, dy: 5, rcl: 2 },
  { type: "extension", dx: 3, dy: 1, rcl: 2 },
  { type: "extension", dx: 4, dy: 1, rcl: 2 },
  { type: "extension", dx: 2, dy: 2, rcl: 2 },
  { type: "extension", dx: 3, dy: 2, rcl: 2 },
  { type: "extension", dx: 2, dy: 3, rcl: 2 },
  { type: "extension", dx: 4, dy: 2, rcl: 3 },
  { type: "extension", dx: 3, dy: 3, rcl: 3 },
  { type: "extension", dx: 4, dy: 3, rcl: 3 },
  { type: "extension", dx: 2, dy: 4, rcl: 3 },
  { type: "extension", dx: 3, dy: 4, rcl: 3 },
  { type: "tower", dx: 0, dy: 1, rcl: 3 },
  { type: "extension", dx: 5, dy: -1, rcl: 4 },
  { type: "extension", dx: 5, dy: 0, rcl: 4 },
  { type: "extension", dx: 5, dy: 1, rcl: 4 },
  { type: "extension", dx: 5, dy: 2, rcl: 4 },
  { type: "extension", dx: 1, dy: 3, rcl: 4 },
  { type: "extension", dx: -1, dy: 4, rcl: 4 },
  { type: "extension", dx: 0, dy: 4, rcl: 4 },
  { type: "extension", dx: -1, dy: 5, rcl: 4 },
  { type: "extension", dx: 0, dy: 5, rcl: 4 },
  { type: "extension", dx: 1, dy: 5, rcl: 4 },
  { type: "road", dx: -2, dy: -6, rcl: 4 },
  { type: "road", dx: -1, dy: -6, rcl: 4 },
  { type: "road", dx: 0, dy: -6, rcl: 4 },
  { type: "road", dx: 1, dy: -6, rcl: 4 },
  { type: "road", dx: 2, dy: -6, rcl: 4 },
  { type: "road", dx: -3, dy: -5, rcl: 4 },
  { type: "road", dx: 3, dy: -5, rcl: 4 },
  { type: "road", dx: -4, dy: -4, rcl: 4 },
  { type: "road", dx: -1, dy: -4, rcl: 4 },
  { type: "road", dx: 4, dy: -4, rcl: 4 },
  { type: "road", dx: -5, dy: -3, rcl: 4 },
  { type: "road", dx: 0, dy: -3, rcl: 4 },
  { type: "road", dx: 5, dy: -3, rcl: 4 },
  { type: "road", dx: -6, dy: -2, rcl: 4 },
  { type: "road", dx: -1, dy: -2, rcl: 4 },
  { type: "road", dx: 1, dy: -2, rcl: 4 },
  { type: "road", dx: 5, dy: -2, rcl: 4 },
  { type: "road", dx: 6, dy: -2, rcl: 4 },
  { type: "road", dx: -6, dy: -1, rcl: 4 },
  { type: "road", dx: -2, dy: -1, rcl: 4 },
  { type: "road", dx: 2, dy: -1, rcl: 4 },
  { type: "road", dx: 4, dy: -1, rcl: 4 },
  { type: "road", dx: 6, dy: -1, rcl: 4 },
  { type: "road", dx: -6, dy: 0, rcl: 4 },
  { type: "road", dx: -3, dy: 0, rcl: 4 },
  { type: "road", dx: 3, dy: 0, rcl: 4 },
  { type: "road", dx: 6, dy: 0, rcl: 4 },
  { type: "road", dx: -6, dy: 1, rcl: 4 },
  { type: "road", dx: -4, dy: 1, rcl: 4 },
  { type: "road", dx: -2, dy: 1, rcl: 4 },
  { type: "road", dx: 2, dy: 1, rcl: 4 },
  { type: "road", dx: 6, dy: 1, rcl: 4 },
  { type: "road", dx: -6, dy: 2, rcl: 4 },
  { type: "road", dx: -5, dy: 2, rcl: 4 },
  { type: "road", dx: -1, dy: 2, rcl: 4 },
  { type: "road", dx: 1, dy: 2, rcl: 4 },
  { type: "road", dx: 6, dy: 2, rcl: 4 },
  { type: "road", dx: -5, dy: 3, rcl: 4 },
  { type: "road", dx: 0, dy: 3, rcl: 4 },
  { type: "road", dx: 5, dy: 3, rcl: 4 },
  { type: "road", dx: -4, dy: 4, rcl: 4 },
  { type: "road", dx: 1, dy: 4, rcl: 4 },
  { type: "road", dx: 4, dy: 4, rcl: 4 },
  { type: "road", dx: -3, dy: 5, rcl: 4 },
  { type: "road", dx: 3, dy: 5, rcl: 4 },
  { type: "road", dx: -2, dy: 6, rcl: 4 },
  { type: "road", dx: -1, dy: 6, rcl: 4 },
  { type: "road", dx: 0, dy: 6, rcl: 4 },
  { type: "road", dx: 1, dy: 6, rcl: 4 },
  { type: "road", dx: 2, dy: 6, rcl: 4 },
  { type: "storage", dx: -1, dy: 0, rcl: 4 },
  { type: "extension", dx: -4, dy: 2, rcl: 5 },
  { type: "extension", dx: -3, dy: 2, rcl: 5 },
  { type: "extension", dx: -2, dy: 2, rcl: 5 },
  { type: "extension", dx: -4, dy: 3, rcl: 5 },
  { type: "extension", dx: -3, dy: 3, rcl: 5 },
  { type: "extension", dx: -2, dy: 3, rcl: 5 },
  { type: "extension", dx: -1, dy: 3, rcl: 5 },
  { type: "extension", dx: -3, dy: 4, rcl: 5 },
  { type: "extension", dx: -2, dy: 4, rcl: 5 },
  { type: "extension", dx: -2, dy: 5, rcl: 5 },
  { type: "link", dx: 1, dy: 1, rcl: 5 },
  { type: "tower", dx: 0, dy: -1, rcl: 5 },
  { type: "extension", dx: -4, dy: -3, rcl: 6 },
  { type: "extension", dx: -5, dy: -2, rcl: 6 },
  { type: "extension", dx: -4, dy: -2, rcl: 6 },
  { type: "extension", dx: -3, dy: -2, rcl: 6 },
  { type: "extension", dx: -5, dy: -1, rcl: 6 },
  { type: "extension", dx: -4, dy: -1, rcl: 6 },
  { type: "extension", dx: -3, dy: -1, rcl: 6 },
  { type: "extension", dx: -5, dy: 0, rcl: 6 },
  { type: "extension", dx: -5, dy: 1, rcl: 6 },
  { type: "extension", dx: -3, dy: 1, rcl: 6 },
  { type: "lab", dx: 2, dy: -2, rcl: 6 },
  { type: "lab", dx: 3, dy: -2, rcl: 6 },
  { type: "lab", dx: 3, dy: -1, rcl: 6 },
  { type: "terminal", dx: 1, dy: 0, rcl: 6 },
  { type: "container", dx: -2, dy: -5, rcl: 7 },
  { type: "extension", dx: 0, dy: -5, rcl: 7 },
  { type: "extension", dx: 1, dy: -5, rcl: 7 },
  { type: "extension", dx: 2, dy: -5, rcl: 7 },
  { type: "extension", dx: -3, dy: -4, rcl: 7 },
  { type: "extension", dx: -2, dy: -4, rcl: 7 },
  { type: "extension", dx: 1, dy: -4, rcl: 7 },
  { type: "extension", dx: -3, dy: -3, rcl: 7 },
  { type: "extension", dx: -2, dy: -3, rcl: 7 },
  { type: "extension", dx: -1, dy: -3, rcl: 7 },
  { type: "extension", dx: -2, dy: -2, rcl: 7 },
  { type: "lab", dx: 3, dy: -3, rcl: 7 },
  { type: "lab", dx: 4, dy: -3, rcl: 7 },
  { type: "lab", dx: 4, dy: -2, rcl: 7 },
  { type: "spawn", dx: 1, dy: -1, rcl: 7 },
  { type: "tower", dx: 0, dy: -2, rcl: 7 },
  { type: "extension", dx: -1, dy: -5, rcl: 8 },
  { type: "lab", dx: 2, dy: -4, rcl: 8 },
  { type: "lab", dx: 3, dy: -4, rcl: 8 },
  { type: "lab", dx: 1, dy: -3, rcl: 8 },
  { type: "lab", dx: 2, dy: -3, rcl: 8 },
  { type: "nuker", dx: -1, dy: -1, rcl: 8 },
  { type: "observer", dx: -4, dy: 0, rcl: 8 },
  { type: "powerSpawn", dx: -1, dy: 1, rcl: 8 },
  { type: "spawn", dx: 0, dy: -4, rcl: 8 },
  { type: "tower", dx: -2, dy: 0, rcl: 8 },
  { type: "tower", dx: 2, dy: 0, rcl: 8 },
  { type: "tower", dx: 0, dy: 2, rcl: 8 }
];

/** 第一个 spawn 相对锚点的位置，respawn 放 spawn 时要对准这里 */
export const FIRST_SPAWN_OFFSET = { dx: 4, dy: 0 };
